// <auto-generated />
using System;
using JoyeriaStock.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JoyeriaStock.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814233510_QuitarPrecioMayorista")]
    partial class QuitarPrecioMayorista
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("PrefijoSku")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("prefijo_sku");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nombre");

                    b.HasIndex("PrefijoSku")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_prefijo_sku");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_locales");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_locales_nombre");

                    b.ToTable("locales", (string)null);
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_utc");

                    b.Property<int>("LocalId")
                        .HasColumnType("integer")
                        .HasColumnName("local_id");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacion");

                    b.Property<decimal?>("PrecioUnitarioAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_unitario_aplicado");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<Guid?>("TransferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("transferencia_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_movimientos");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_movimientos_producto_id");

                    b.HasIndex("TransferenciaId")
                        .HasDatabaseName("ix_movimientos_transferencia_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_movimientos_usuario_id");

                    b.HasIndex("LocalId", "FechaUtc")
                        .HasDatabaseName("ix_movimientos_local_id_fecha_utc");

                    b.ToTable("movimientos", (string)null);
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoLinea")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("codigo_linea");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_base");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sku");

                    b.Property<int>("UmbralStockBajo")
                        .HasColumnType("integer")
                        .HasColumnName("umbral_stock_bajo");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_productos_sku");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int>("LocalId")
                        .HasColumnType("integer")
                        .HasColumnName("local_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.HasKey("ProductoId", "LocalId")
                        .HasName("pk_stocks");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_stocks_local_id");

                    b.ToTable("stocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_stocks_cantidad_no_negativa", "cantidad >= 0");
                        });
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<int?>("LocalId")
                        .HasColumnType("integer")
                        .HasColumnName("local_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("LocalId")
                        .HasDatabaseName("ix_usuarios_local_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("JoyeriaStock.Api.Domain.Entities.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_locales_local_id");

                    b.HasOne("JoyeriaStock.Api.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_productos_producto_id");

                    b.HasOne("JoyeriaStock.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_usuarios_usuario_id");

                    b.Navigation("Local");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Producto", b =>
                {
                    b.HasOne("JoyeriaStock.Api.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Stock", b =>
                {
                    b.HasOne("JoyeriaStock.Api.Domain.Entities.Local", "Local")
                        .WithMany("Stocks")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stocks_locales_local_id");

                    b.HasOne("JoyeriaStock.Api.Domain.Entities.Producto", "Producto")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stocks_productos_producto_id");

                    b.Navigation("Local");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("JoyeriaStock.Api.Domain.Entities.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuarios_locales_local_id");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Local", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("JoyeriaStock.Api.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
